name: Build Asistencia V3 (Camera4Kivy)
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # 1. Limpieza
      - name: Free Disk Space
        run: |
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /opt/ghc
          sudo rm -rf "/usr/local/share/boost"

      # 2. Java
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      # 3. Dependencias b√°sicas (Ya no necesitamos las complejas de zbar)
      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential git python3-pip python3-dev libffi-dev libssl-dev

      # 4. Buildozer
      - name: Install Buildozer
        run: |
          pip3 install --upgrade pip
          pip3 install --user --upgrade Cython==0.29.33 virtualenv buildozer

      # 5. Compilar
      - name: Build APK
        run: |
          export PATH=$PATH:~/.local/bin
          buildozer android debug

      # 6. Subir
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: Asistencia-V3-APK
          path: bin/*.apk
